id: ans.fhir.fr.agenda
canonical: https://interop.esante.gouv.fr/ig/fhir/agenda
name: Gestion d'Agenda Partagé 
title: Gestion d'Agenda Partagé (GAP)
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
  shownav: 'true'

dependencies:
  hl7.fhir.fr.core: 
    uri: https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/snapshots/$download
    version: 1.1.0



pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        construction_des_flux.md:
        flux1.md:
            title: Flux 01
        flux2.md:
            title: Flux 02
        flux3.md:
            title: Flux 03
        flux4.md:
            title: Flux 04
        flux5.md:
            title: Flux 05
        flux6.md:
            title: Flux 06
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    tests.md:
        title: Tests      
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Description des flux:
        Construction des flux: construction_des_flux.html
        Flux 01: flux1.html
        Flux 02: flux2.html
        Flux 03: flux3.html
        Flux 04: flux4.html
        Flux 05: flux5.html
        Flux 06: flux6.html
    Ressources de conformité: artifacts.html
    Tests:   tests.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html