id: ans.fhir.fr.agenda
canonical: https://interop.esante.gouv.fr/ig/fhir/agenda
name: Gestion d'Agenda Partagé 
title: Gestion d'Agenda PArtagé (GAP)
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

parameters:
  shownav: 'true'

dependencies:
  hl7.fhir.fr.core: 
    uri: https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/snapshots/$download
    version: 1.1.0