name: Workflow Init ANS
on:
  workflow_call:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:      
          path: igSource
      - uses: M-Priour/IG-workflows@main
        with:      
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_ig: igSource
          bake: "true"
          nos: "true"
          validator_cli: "true"
      
